namespace LittleberryApi.Models.DTOs;

public class QuoteRequest
{
    public string? Title { get; set; }
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? BirthDate { get; set; }
    public string? Employer { get; set; }
    public string? Occupation { get; set; }
    public string? Email { get; set; }
    public string? Phone { get; set; }
    public string? MaritalStatus { get; set; }
    public string? Address1 { get; set; }
    public string? Address2 { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? PostalCode { get; set; }
    public string? D1Name { get; set; }
    public string? D1Birth { get; set; }
    public string? D1Description { get; set; }
    public string? D1AnnualCost { get; set; }
    public string? D1SetAside { get; set; }
    public string? D1SetAside529 { get; set; }
    public string? D1YouPay { get; set; }
    public string? D1StartAge { get; set; }
    public string? D1YearsNeeded { get; set; }
    public string? D2Name { get; set; }
    public string? D2Birth { get; set; }
    public string? D2Description { get; set; }
    public string? D2AnnualCost { get; set; }
    public string? D2SetAside { get; set; }
    public string? D2SetAside529 { get; set; }
    public string? D2YouPay { get; set; }
    public string? D2StartAge { get; set; }
    public string? D2YearsNeeded { get; set; }
    public string? D3Name { get; set; }
    public string? D3Birth { get; set; }
    public string? D3Description { get; set; }
    public string? D3AnnualCost { get; set; }
    public string? D3SetAside { get; set; }
    public string? D3SetAside529 { get; set; }
    public string? D3YouPay { get; set; }
    public string? D3StartAge { get; set; }
    public string? D3YearsNeeded { get; set; }
    public string? D4Name { get; set; }
    public string? D4Birth { get; set; }
    public string? D4Description { get; set; }
    public string? D4AnnualCost { get; set; }
    public string? D4SetAside { get; set; }
    public string? D4SetAside529 { get; set; }
    public string? D4YouPay { get; set; }
    public string? D4StartAge { get; set; }
    public string? D4YearsNeeded { get; set; }
    public string? D5Name { get; set; }
    public string? D5Birth { get; set; }
    public string? D5Description { get; set; }
    public string? D5AnnualCost { get; set; }
    public string? D5SetAside { get; set; }
    public string? D5SetAside529 { get; set; }
    public string? D5YouPay { get; set; }
    public string? D5StartAge { get; set; }
    public string? D5YearsNeeded { get; set; }
    public string? BeforeTaxInvestmentReturn { get; set; }
    public string? MarginalTaxBracket { get; set; }
    public string? CollegeCostInflation { get; set; }
    public string? AnnualIncreaseInContribution { get; set; }
}
